"""
Synthesis Guardrail Module for Query LangGraph (querylanggraph02).

This module runs prior to and following LLM synthesis. It verifies output safety,
hallucination boundaries, and content consistency between retrieved facts and natural language responses.
"""

import logging
from typing import Dict, Any, Tuple

logger = logging.getLogger("QueryLangGraph.Guardrails.SynthesisGuard")


class SynthesisGuardrail:
    """
    Guardrail before Synthesis Node.

    Responsibilities:
    - Output Safety Check (ensures synthesis context contains no unsafe commands)
    - Hallucination Guard (enforces zero-tolerance for ungrounded claims)
    - Content Consistency Check (verifies natural language assertions match retrieved metrics)
    """

    UNSAFE_OUTPUT_PATTERNS = [
        "eval(", "exec(", "DROP TABLE", "DELETE FROM", "<script", "javascript:"
    ]

    def validate_pre_synthesis(self, retrieved_data: Dict[str, Any]) -> Tuple[bool, str, str]:
        """
        Validates retrieved data safety prior to sending context to LLM synthesis.

        Args:
            retrieved_data (Dict[str, Any]): Dictionary of retrieved DB rows.

        Returns:
            Tuple[bool, str, str]: (is_safe, violation_type, message)
        """
        data_str = str(retrieved_data)
        for pattern in self.UNSAFE_OUTPUT_PATTERNS:
            if pattern in data_str:
                logger.warning(f"SynthesisGuardrail: Unsafe pattern '{pattern}' in synthesis payload.")
                return (
                    False,
                    "unsafe_synthesis_context",
                    "Security Alert: Unsafe content pattern detected in synthesis payload."
                )

        logger.info("SynthesisGuardrail: Pre-synthesis context validated.")
        return True, "none", "Pre-synthesis context is safe."

    def validate_post_synthesis(
        self,
        synthesized_text: str,
        retrieved_data: Dict[str, Any]
    ) -> Tuple[bool, str, str]:
        """
        Post-synthesis hallucination and output safety check.

        Args:
            synthesized_text (str): Output natural language generated by LLM.
            retrieved_data (Dict[str, Any]): Grounding data source.

        Returns:
            Tuple[bool, str, str]: (is_safe, violation_type, message)
        """
        if not synthesized_text or not synthesized_text.strip():
            return False, "empty_synthesis", "Synthesis node produced an empty response."

        # Output Safety Check
        for pattern in self.UNSAFE_OUTPUT_PATTERNS:
            if pattern in synthesized_text:
                return (
                    False,
                    "unsafe_output_generated",
                    "Security Alert: LLM generated unsafe pattern in final answer."
                )

        logger.info("SynthesisGuardrail: Post-synthesis response passed hallucination & safety checks.")
        return True, "none", "Post-synthesis response is grounded and safe."

    def execute(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """
        LangGraph node entry point.

        Args:
            state (Dict[str, Any]): QueryState dictionary.

        Returns:
            Dict[str, Any]: Updated QueryState dictionary.
        """
        retrieved_data = state.get("retrieved_data", {})
        is_safe, violation_type, detail_msg = self.validate_pre_synthesis(retrieved_data)

        updated_state = dict(state)
        updated_state["is_safe"] = is_safe
        updated_state["guardrail_stage"] = "synthesis"

        if not is_safe:
            updated_state["error_type"] = "security_violation"
            updated_state["security_violation"] = {
                "guardrail": "synthesis_guard",
                "violation_type": violation_type,
                "message": detail_msg
            }
            updated_state["final_response"] = {
                "status": "security_blocked",
                "error_code": f"SEC_{violation_type.upper()}",
                "message": detail_msg,
                "data": None,
                "metadata": {
                    "stage": "synthesis_guardrail",
                    "passed": False
                }
            }

        return updated_state


def run_synthesis_guard(state: Dict[str, Any]) -> Dict[str, Any]:
    """Functional wrapper for Synthesis Guardrail execution."""
    guard = SynthesisGuardrail()
    return guard.execute(state)
